/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.5).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package org.intermine.webservice.api;

import org.intermine.webservice.model.Branding;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2019-06-17T02:38:26.046+05:30[Asia/Kolkata]")
@Api(value = "branding", description = "the branding API")
public interface BrandingApi {

    @ApiOperation(value = "Get Branding Information.", nickname = "branding", notes = "Retrieve branding information, so that elements may be visually styled appropriately for their source.", response = Branding.class, tags={ "Branding" })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Branding.class) })
    @RequestMapping(value = "/branding",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Branding> branding();

}
