/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.5).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package org.intermine.webservice.api;

import io.swagger.annotations.*;
import org.intermine.webservice.model.SummaryFields;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import javax.validation.Valid;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2019-05-26T23:19:30.817+05:30[Asia/Kolkata]")
@Api(value = "summaryFields", description = "the summaryFields API")
public interface SummaryFieldsApi {

    @ApiOperation(value = "Get the fields used to summarise the class.", nickname = "summaryFields", notes = "", response = SummaryFields.class, tags={ "Summary Fields" })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = SummaryFields.class) })
    @RequestMapping(value = "/summaryfields",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<SummaryFields> summaryfields(@ApiParam(value = "Whether to exclude references from the summary fields") @Valid @RequestParam(value = "norefs", required = false) Boolean norefs);

}
