/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.5).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package org.intermine.webservice.api;

import io.swagger.annotations.*;
import org.intermine.webservice.model.Summaryfields;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import javax.validation.Valid;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2019-05-26T23:19:30.817+05:30[Asia/Kolkata]")
@Api(value = "summaryfields", description = "the summaryfields API")
public interface SummaryfieldsApi {

    @ApiOperation(value = "Get the fields used to summarise the class.", nickname = "summaryfields", notes = "", response = Summaryfields.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Summaryfields.class) })
    @RequestMapping(value = "/summaryfields",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Summaryfields> summaryfields(@ApiParam(value = "Whether to exclude references from the summary fields") @Valid @RequestParam(value = "norefs", required = false) Boolean norefs);

}
