/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.5).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package org.intermine.webservice.api;

import org.intermine.webservice.model.WebProperties;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2019-06-18T03:15:59.349+05:30[Asia/Kolkata]")
@Api(value = "web-properties", description = "the web-properties API")
public interface WebPropertiesApi {

    @ApiOperation(value = "Get a description of the data model.", nickname = "webProperties", notes = "The InterMine user interface can be customised with a set of properties, e.g. default values for the list upload, default values for the region search etc.", response = WebProperties.class, tags={ "WebProperties" })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = WebProperties.class) })
    @RequestMapping(value = "/web-properties",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<WebProperties> webProperties();

}
