/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.5).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package org.intermine.webservice.api;

import org.intermine.webservice.model.Widgets;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2019-07-20T18:29:46.239+05:30[Asia/Kolkata]")
@Api(value = "widgets", description = "the widgets API")
public interface WidgetsApi {

    @ApiOperation(value = "Get a list of the widgets available at a service.", nickname = "widgetsGet", notes = "This service returns a list of the widgets that are available at a         given service. Each entry for the widget includes details of its type,         the kind of data it processes, and any filters it accepts.", response = Widgets.class, tags={ "Widgets" })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Widgets.class) })
    @RequestMapping(value = "/widgets",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<?> widgetsGet(@ApiParam(value = "", allowableValues = "json, xml, tab, csv") @Valid @RequestParam(value = "format", required = false, defaultValue = "json") String format);

}
